### ISSUE TITLE
Please prepare bundle for OCP 4.4

### ISSUE THREAD

**Issue by sosiouxme** [openshift/ptp-operator#24]
Now that we are fully branched for 4.4, please prepare your operator to supply a 4.4 bundle, so that 4.4 operator publishing works and doesn't overwrite 4.3 bundles. This means at least updating the package.yaml under https://github.com/openshift/ptp-operator/tree/master/manifests
@zshi-redhat

**Comment by sosiouxme** [comment]
@zshi-redhat re-ping on this. You'll come to me wondering why your operator isn't building downstream...

**Comment by zshi-redhat** [comment]
@sosiouxme I made a PR and added you as reviewer, please help to take a look: https://github.com/openshift/ptp-operator/pull/25

**Comment by sosiouxme** [comment]
it merged.
